### ISSUE TITLE
Failed - Can not determine main classes output directory?

### ISSUE THREAD

**Issue by ghost** [ebean-orm-tools/ebean-init#2]
thanks for your tools, make things easier.

the project git is https://gitee.com/david0624/simpleBenchmark

I find if the idea ide out directory doesn't have a class file,show this error.
so I simple write a hello world to run,and generate a out directory have class file,
the error disappear.
I wonder why generate java file,need the main classes output directory?
what are the best practises?

**Comment by jnehlmeier** [comment]
The issue is that the tool only checks for `target/classes` and `out/production/classes` which basically matches Maven or IntelliJ. For Gradle it should also check `build/classes/java/main` and for eclipse possibly `bin` (or similar, haven't used Eclipse for a long time).

Recent versions of IntelliJ delegate build actions to Gradle by default if a Gradle project has been imported. In that case `out/production/classes` will never be created by IntelliJ and only the Gradle output exists.

**Comment by ghost** [comment]
@jnehlmeier thanks a lot,I find that , I should build project first ,it use .class files to analyse,
